### ISSUE TITLE
Updates Integration

### ISSUE THREAD

**Issue by ahmedkaludi** [TheSkin/Skin-WordPress-Theme#13]

**Comment by MohammedKaludi** [comment]
need plugin from @ahmedkaludi

**Comment by ahmedkaludi** [comment]
@MohammedKaludi  We will use Wp Pusher, i have sent you the plugin via hipchat. see docs at https://github.com/wppusher/wppusher-documentation

**Comment by ahmedkaludi** [comment]
Updates added to theme and plugin via Autohosted at Magazine3.com updates server.
Theme: c70fdcb0970c8e0df17d334659e939e8a92d618d
Plugin: 53154a697c0f0e87978adcdabcc8e754aeda4fb9
